checks:
  php: true

build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.3
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
          - command: "./vendor/bin/phpunit --configuration phpunit.xml --testsuite scrutinizer"

  dependencies:
    override:
      - composer install --ignore-platform-reqs --no-interaction